version: '3.4'

services:
  courseworkmain:
    image: ${DOCKER_REGISTRY-}courseworkmain
    build:
      context: .
      dockerfile: CourseWorkMain/Dockerfile
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=2Secure*Password2
      - ACCEPT_EULA=Y
    ports:
      - "1440:1433"