// <auto-generated />
using CourseWorkMain.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseWorkMain.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221223221824_Migration2")]
    partial class Migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseWorkMain.Models.Locality", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<int>("Budget1")
                        .HasColumnType("int");

                    b.Property<string>("Mayor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberResidants")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Localities");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Budget = 100000,
                            Budget1 = 50,
                            Mayor = "Владимир Васильевич Марченко",
                            Name = "Волгоград",
                            NumberResidants = 100000,
                            Type = "City"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
