// <auto-generated />
using CourseWorkMain.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseWorkMain.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230113224326_Migration5")]
    partial class Migration5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseWorkMain.Models.BusinessTrip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Employee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wage")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("BusinessTrips");

                    b.HasData(
                        new
                        {
                            id = 1,
                            City = "Волгоград",
                            Days = 15,
                            Employee = "Владимир Васильевич Марченко",
                            Wage = 100000
                        },
                        new
                        {
                            id = 2,
                            City = "Севастополь",
                            Days = 30,
                            Employee = "Михаил Михайлович Минин",
                            Wage = 20000
                        },
                        new
                        {
                            id = 3,
                            City = "Москва",
                            Days = 25,
                            Employee = "Беляев Рудольф Максович",
                            Wage = 130000
                        },
                        new
                        {
                            id = 4,
                            City = "Волгоград",
                            Days = 11,
                            Employee = "Гусев Святослав Антонович",
                            Wage = 10000
                        },
                        new
                        {
                            id = 5,
                            City = "Крым",
                            Days = 17,
                            Employee = "Муравьёв Роман Семенович",
                            Wage = 100600
                        },
                        new
                        {
                            id = 6,
                            City = "Вологда",
                            Days = 31,
                            Employee = "Гусев Святослав Антонович",
                            Wage = 100000
                        },
                        new
                        {
                            id = 7,
                            City = "Воронеж",
                            Days = 15,
                            Employee = "Андреев Лавр Иосифович",
                            Wage = 100000
                        },
                        new
                        {
                            id = 8,
                            City = "Калининград",
                            Days = 5,
                            Employee = "Беляев Рудольф Максович",
                            Wage = 15000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
